### ISSUE TITLE
集成进去后报错

### ISSUE THREAD

**Issue by 939582415** [sunfusheng/GlideImageView#55]
Caused by: java.lang.IllegalStateException: You cannot call Glide.get() in registerComponents(), use the provided Glide instance instead
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:178)
        at com.bumptech.glide.Glide.get(Glide.java:166)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:680)
        at com.bumptech.glide.Glide.with(Glide.java:707)
        at com.sunfusheng.progress.GlideApp.with(GlideApp.java:88)
        at com.sunfusheng.GlideImageLoader.<init>(GlideImageLoader.java:42)
        at com.sunfusheng.GlideImageLoader.create(GlideImageLoader.java:37)
        at com.sunfusheng.GlideImageView.init(GlideImageView.java:43)
        at com.sunfusheng.GlideImageView.<init>(GlideImageView.java:39)
        at com.sunfusheng.GlideImageView.<init>(GlideImageView.java:34)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:597)

**Comment by sunfusheng** [comment]
应该是混淆的问题，加一下如下的混淆命令：
-keep class com.bumptech.glide.GeneratedAppGlideModuleImpl { *; }
